# try to access dictionary key that doesn't exist


# user = {"name": "akash"}
# print(user["age"]) -> KeyError: 'age'